### ISSUE TITLE
User can select other app than ODK Collect to send finalized form

### ISSUE THREAD

**Issue by mmarciniak90** [grzesiek2010/collectTester#9]
### Use Case
1. User clicks on 'Send finalized form' button
2. User sees a view with list of apps 
3. User can select which app opens this activity

### Actual Result
User is able to open this activity by really unexpected apps
![screenshot_20171004-095246](https://user-images.githubusercontent.com/3907554/31167479-81aa96b8-a8f2-11e7-9cf0-93fae4296e45.png)

### Expected result
ODK Collect opens as a default app

**Comment by grzesiek2010** [comment]
@mmarciniak90 @lognaturel 
That's because there is no any type specified in [InstanceUploaderActivity](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/AndroidManifest.xml#L176)

It works well for other buttons because I can use type there like:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/AndroidManifest.xml#L148
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/AndroidManifest.xml#L161

@lognaturel is that a bug on Collect side we don't have that type?
